# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
