# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170312_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attached_file',
        ),
    ]
