# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170323_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(to='blogs.Post'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='Anything', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
