# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170327_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(to='blogs.Blog'),
        ),
    ]
