# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170327_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='posts',
            new_name='blogs',
        ),
    ]
